name: peemart
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.1.1
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  uuid: ^4.4.0
  carousel_slider: ^4.2.1
  video_player: ^2.7.0
  fl_chart: ^0.68.0
  flutter_fortune_wheel: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/bg.jpg

  fonts:
    - family: Skiwar
      fonts:
        - asset: assets/fonts/SkiwarRegular-woOan.otf

    - family: Believe Stronger Personal Use Only
      fonts:
        - asset: assets/fonts/BelieveStrongerPersonalUseOnlyRegular-aYdXK.ttf
    
    - family: Creatball
      fonts:
        - asset: assets/fonts/CreatballItalic-5yBPj.ttf

    - family: Quicking
      fonts:
        - asset: assets/fonts/QuickingRegular-gw5KY.otf

    - family: Molgan
      fonts:
        - asset: assets/fonts/MolganRegular-YqWj2.otf

    - family: Swansea    
      fonts:
        - asset: assets/fonts/Swansea-q3pd.ttf
     